kafka.topic.rushi-new-topic: rushi-new-topic
spring:
  kafka:
    bootstrap-servers: localhost:9092,localhost:9094
    consumer:
      group-id: ${spring.application.name}
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      max-poll-records : 100
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.LongSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      properties:
#        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.LongDeserializer
#        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
#        spring.serializer.key.delegate.class: org.apache.kafka.common.serialization.LongSerializer
#        spring.serializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonSerializer
#        spring.json.trusted.packages: "*"
#        spring.json.value.default.type: com.kafka.notification_service.event.UserCreatedEvent
#        spring.json.add.type.headers: true
app:
  kafka:
    user-created:
      group-id: user-created-group
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      trusted-packages: com.kafka.notification_service.event
      value-default-type: com.kafka.notification_service.event.UserCreatedEvent
      retry:
        backoff:
          delay: 2000
        max:
          attempt: 3